src/main/kotlin/com/vaadin/plugin/copilot/CopilotPluginUtil.kt
Creates .idea directory if not yet initialized by IntelliJ itself.
Can be tested using:
[intellij-plugin-1.0-SNAPSHOT.zip](https://github.com/vaadin/intellij-plugin/files/14664756/intellij-plugin-1.0-SNAPSHOT.zip)
Fixes #13
=> fix: create .idea directory if missing

src/main/kotlin/com/vaadin/plugin/copilot/handler/WriteFileHandler.kt
Open editor when saving file contents
Fixes https://github.com/vaadin/copilot-internal/issues/1817
=> chore: open editor after file has been saved

src/main/kotlin/com/vaadin/plugin/copilot/handler/WriteFileHandler.kt
Use IntelliJ line separator converter before saving file 
Fixes #44
=> fix: convert new lines to match intellij

build.gradle.kts
As in title,  to be in line with https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html#requirements
=> chore: lower supported version to 2022.3

.github/workflows/validation.yml, build.gradle.kts
Due to incompatibility of SegmentButton API in versions 223 and 233 I needed to rollback previous version lowering.
=> chore: use compatible versions

src/main/kotlin/com/vaadin/plugin/actions/VaadinCompileOnSaveAction.kt, src/main/kotlin/com/vaadin/plugin/actions/VaadinCompileOnSaveActionInfo.kt, src/main/kotlin/com/vaadin/plugin/actions/VaadinOnSaveInfoProvider.kt, src/main/kotlin/com/vaadin/plugin/copilot/handler/RedoHandler.kt, src/main/kotlin/com/vaadin/plugin/copilot/handler/ShowInIdeHandler.kt, src/main/kotlin/com/vaadin/plugin/copilot/handler/UndoHandler.kt, src/main/kotlin/com/vaadin/plugin/copilot/handler/WriteFileHandler.kt, src/main/kotlin/com/vaadin/plugin/copilot/service/CopilotRestService.kt, src/main/resources/META-INF/plugin.xml
In this PR:
- added action on save that monitors user file modifications and performs single file compilation (for `.java` files only)
- removed `runInEdt{ }` for all plugin handlers, now run as small parts as possible in event dispatch thread
- writeFile triggers compile
Fixes https://github.com/vaadin/copilot-internal/issues/2968
=> feat: Compile on save

src/main/kotlin/com/vaadin/plugin/actions/InstallOrUpdateHotSwapAction.kt, src/main/kotlin/com/vaadin/plugin/activity/ConfigurationCheckPostStartupProjectActivity.kt, src/main/kotlin/com/vaadin/plugin/utils/VaadinHomeUtil.kt, src/main/resources/META-INF/plugin.xml
hotswap-agent.jar is being installed or updated once for given plugin version. In case of missing file user can now just call HotSwap: Install or update action to bring it back.
=> chore: bring back RunOnce, add action to manually install or update hotswap-agent.jar

src/main/kotlin/com/vaadin/plugin/copilot/CopilotPluginUtil.kt, src/main/kotlin/com/vaadin/plugin/copilot/activity/CopilotPostStartupProjectActivity.kt, src/main/kotlin/com/vaadin/plugin/utils/VaadinProjectUtil.kt, src/main/resources/META-INF/plugin.xml
Use IntelliJ API to detect Vaadin dependency
Tested with both Maven and Gradle based projects
=> fix: checks if project is Vaadin project based on modules libraries

src/main/kotlin/com/vaadin/plugin/actions/DebugUsingHotSwapAgentAction.kt, src/main/resources/META-INF/plugin.xml
Now you can Debug with HotSwapAgent from Services menu:
Fixes #76
=> feat: add debug using hotswap to run toolbar

src/main/kotlin/com/vaadin/plugin/hotswapagent/HotswapAgentProgramPatcher.kt
The default value for frame deactivation is to update classes and resources.
This causes an extra update when going from IntelliJ to the browser which either does nothing or then does an extra hotswap of some files, as described in https://github.com/vaadin/flow/issues/19971
Fixes https://github.com/vaadin/flow/issues/19971
=> fix: Turn off frame deactivation policy for Spring apps

build.gradle.kts
Hello Vaadin Ltd,
We noticed that due to a limited Until range, the following plugins will not be compatible with the upcoming IDE version (2024.3):
[Vaadin](https://plugins.jetbrains.com/plugin/23758-vaadin)
The EAP version was just released, so you have time to address the issue by uploading a new version with a higher or unlimited 'Until Build' setting.
We kindly suggest that you adjust the compatibility range to enable current users to continue enjoying the functionalities of your plugin without any interruptions.
Moreover, updating the compatibility settings will also make your plugin discoverable to new users who are exploring the latest version of our IDE.
Please feel free to reach out if you have any questions or require further assistance.
You can unsubscribe from future …
=> chore: increase until to 243.*

src/main/kotlin/com/vaadin/plugin/copilot/CopilotErrorHandler.kt
=> fix: trim stacktrace to fit in GH issue description

src/main/kotlin/com/vaadin/plugin/actions/DebugUsingHotSwapAgentAction.kt, src/main/resources/META-INF/plugin.xml
Added Debug/Rerun using HotSwap to debugger toolbar:
When debugging with hotswap is running, label now displays "Rerun":
Fixes #92
=> chore: add to debugger toolbar, rerun label

src/main/kotlin/com/vaadin/plugin/VaadinProjectDetector.kt
Library roots can be changed before project is loaded. We need to discard those events on not opened project. Project post startup activity will trigger event if ready. 
Fixes #100
=> Do not create copilot dotfile if project is not opened yet

src/main/kotlin/com/vaadin/plugin/copilot/CopilotPluginUtil.kt, src/main/kotlin/com/vaadin/plugin/copilot/listeners/CopilotVaadinProjectListener.kt
Use VirtualFile to save `.copilot-plugin.properties` file.
Based on [contribution](https://github.com/vaadin/intellij-plugin/issues/47#issuecomment-2386479560) by @sveinnetnordic
Fixes #47
=> fix: Use VirtualFiles to save dot file, improved logging

.github/workflows/validation.yml, .idea/codeStyles/Project.xml, build.gradle.kts, src/main/kotlin/com/vaadin/plugin/copilot/handler/AbstractHandler.kt, src/main/kotlin/com/vaadin/plugin/copilot/handler/RedoHandler.kt, src/main/kotlin/com/vaadin/plugin/copilot/handler/UndoHandler.kt, src/main/kotlin/com/vaadin/plugin/copilot/handler/WriteBase64FileHandler.kt, src/main/kotlin/com/vaadin/plugin/copilot/handler/WriteFileHandler.kt, src/main/kotlin/com/vaadin/plugin/copilot/service/CopilotUndoManager.kt, src/main/kotlin/com/vaadin/plugin/copilot/service/CopilotUndoManagerImpl.kt, src/main/resources/META-INF/plugin.xml, src/test/kotlin/com/vaadin/plugin/copilot/service/CopilotUndoManagerTest.kt
Use approach similar to VS Code plugin to track file changes in our own service. Assumed that file writes that happen after given time window are invoked by IDE as save actions. Window size set to 1000 ms.
=> fix: CopilotUndoManager service for tracking actions on save

src/main/kotlin/com/vaadin/plugin/actions/VaadinCompileOnSaveAction.kt
=> fix: bring back HotSwapUI wrapper

src/main/kotlin/com/vaadin/plugin/actions/VaadinCompileOnSaveAction.kt
`WriteIntentReadAction` cannot be used in background threads. Read action is enough for calling HotSwapUI.
=> fix: Do not use write locking access when running in background

src/main/kotlin/com/vaadin/plugin/hotswapagent/JdkUtil.kt
Should match also -jcef and other variants
=> fix: Relax check for version and build in JBR version

src/main/kotlin/com/vaadin/plugin/copilot/listeners/CopilotVaadinProjectListener.kt
There are cases that this action is not run within EDT, must be wrapped explicitly
=> chore: Wrap file write action in EDT

src/main/kotlin/com/vaadin/plugin/listeners/ConfigurationCheckVaadinProjectListener.kt
Fixes https://github.com/vaadin/copilot-internal/issues/3706
After update:
=> chore: rephrase VCS confirmation popup

src/main/kotlin/com/vaadin/plugin/actions/VaadinCompileOnSaveAction.kt
See https://youtrack.jetbrains.com/issue/JBR-7850/Calling-compile-from-a-save-action-can-trigger-another-save-action
Fixes #147
=> fix: Make it less likely to trigger multiple compiles

build.gradle.kts
Removes max version limitation. Otherwise we need to bump it on each new intellij release.
=> chore: Removes untilBuild property

build.gradle.kts, src/main/kotlin/com/vaadin/plugin/copilot/CopilotPluginUtil.kt, src/main/kotlin/com/vaadin/plugin/copilot/handler/AbstractHandler.kt, src/main/kotlin/com/vaadin/plugin/copilot/handler/GetModulePathsHandler.kt
To check if a file was inside the project we were only checking the project base folder which is not accurate when the project has external modules.
The fix looks in every module in the project including the base project. 
Fixes #163
=> fix: check every module when looking if a file is inside the project

build.gradle.kts
Update intellij platform to 2.1.0. Reorder build.gradle.kts due to https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1784
=> chore: Update intellij platform

src/main/kotlin/com/vaadin/plugin/VaadinProjectDetector.kt, src/main/kotlin/com/vaadin/plugin/endpoints/VaadinEndpointsProvider.kt, src/main/kotlin/com/vaadin/plugin/endpoints/VaadinModel.kt, src/main/kotlin/com/vaadin/plugin/endpoints/VaadinUrlResolver.kt, src/main/kotlin/com/vaadin/plugin/utils/VaadinProjectUtil.kt
Use `hasLibraryClass` to detect Vaadin. Should be more reliable and faster than previous solution.
Fixes #166
=> ref: use hasLibraryClass to detect Vaadin projects

src/main/kotlin/com/vaadin/plugin/actions/DebugUsingHotSwapAgentAction.kt, src/main/kotlin/com/vaadin/plugin/hotswapagent/HotswapAgentExecutor.kt
Filtering HotSwap option launcher for non Java Run configurations (maven/gradle). This PR fixes the issue for the standard launch toolbar and the services window. 
We would fix the issue for other windows (Maven/Gradle) in a subsequent PR because it requires further investigation. 
Check the video for expected result 
Fixes #144 
https://github.com/user-attachments/assets/d2a1f7aa-1359-4cf6-bf7b-ea6b61ba0c6f
=> fix: hotswap only for java run configurations

src/main/kotlin/com/vaadin/plugin/hotswapagent/HotswapAgentExecutor.kt
Disable Hotswap option when a non java run configuration (Maven/Gradle) is selected in the Run/debug toolbar.
Fixes #144
=> fix: filtering HotSwap option in Run/Debug toolbar for non Java run configurations

src/main/kotlin/com/vaadin/plugin/copilot/CopilotPluginUtil.kt
Fixes https://github.com/vaadin/copilot/issues/51
=> fix: Detect Gradle source folders correctly

src/main/kotlin/com/vaadin/plugin/utils/VaadinProjectUtil.kt
=> Fix: NPE on not found endpoints plugin id

build.gradle.kts, src/main/kotlin/com/vaadin/plugin/symbols/HillaSymbol.kt, src/main/kotlin/com/vaadin/plugin/symbols/HillaSymbolReference.kt, src/main/kotlin/com/vaadin/plugin/symbols/HillaSymbolReferenceProvider.kt, src/main/resources/META-INF/plugin.xml, src/main/resources/META-INF/vaadin-with-javascript.xml
Implemented one way navigation from TypeScript files to Hilla services implementation using Symbol API.
To test open any TypeScript view file and CMD+Click on service name or service method name. Editor should be opened on proper file and line.
=> feat: Hilla TS to BrowserCallable Java symbol references

src/main/kotlin/com/vaadin/plugin/ui/VaadinStatusBarWidget.kt
=> fix: correct popup position

src/main/kotlin/com/vaadin/plugin/copilot/CopilotPluginUtil.kt, src/main/kotlin/com/vaadin/plugin/copilot/handler/RestartApplicationHandler.kt
=> feat: restartApplication command

src/main/kotlin/com/vaadin/plugin/copilot/listeners/CopilotDynamicPluginListener.kt, src/main/resources/META-INF/plugin.xml
This PR fixes issue when plugin is Enabled and Disabled leaving `.copilot-plugin` not removed or created.
Fixes: #296 
Fixes: #295
=> fix: Use DynamicPluginListener to create and remove .copilot-plugin

src/main/kotlin/com/vaadin/plugin/copilot/handler/ShowInIdeHandler.kt
=> chore: Throw bad request when line or column have negative values

src/main/kotlin/com/amplitude/ampli/Ampli.kt, src/main/kotlin/com/vaadin/plugin/VaadinProjectDetector.kt, src/main/kotlin/com/vaadin/plugin/copilot/listeners/CopilotVaadinProjectListener.kt, src/main/kotlin/com/vaadin/plugin/ui/VaadinStatusBarInfoPopupPanel.kt, src/main/kotlin/com/vaadin/plugin/ui/VaadinStatusBarWidget.kt, src/main/kotlin/com/vaadin/plugin/utils/AmpliUtil.kt, src/main/kotlin/com/vaadin/plugin/utils/VaadinHomeUtil.kt, src/main/kotlin/com/vaadin/plugin/utils/VaadinProjectUtil.kt
=> chore: Include proKey and vaadiner information in statistic requests

src/main/kotlin/com/vaadin/plugin/copilot/CopilotPluginUtil.kt, src/main/kotlin/com/vaadin/plugin/copilot/handler/DeleteFileHandler.kt, src/main/kotlin/com/vaadin/plugin/copilot/handler/UndoHandler.kt
Adding delete file handler, needed for copilot (ext) project to be able to handle cases when we want to undo cases where we added a new file.
=> feat: Adding Delete file command

plugin/src/main/kotlin/com/vaadin/plugin/psi/HillaReferenceSearcher.kt, plugin/src/main/resources/META-INF/vaadin-with-javascript.xml
Allows navigating from Hilla method reference to TypeScript.
nit: there is a bug somewhere because above method you see 4 usages and in popup there are 2...
=> feat: Allows navigating from Java to TypeScript

plugin/src/main/kotlin/com/vaadin/plugin/VaadinProjectDetector.kt, plugin/src/main/kotlin/com/vaadin/plugin/copilot/listeners/CopilotVaadinProjectListener.kt, plugin/src/main/resources/META-INF/plugin.xml
Until now, Vaadin has been detected:
- on project opened
- on modules updated (dependencies)
Issue was that for new projects none of above worked due to indexing not finished.
This PR adds indexing finished (dumb mode) listener. For performance reasons existing methods have been moved to background thread.
Fixes: #354 
Fixes: #191
To test create new Vaadin project and wait until indexing is finished.
=> fix: Detect Vaadin on new projects

plugin/src/main/kotlin/com/vaadin/plugin/copilot/service/CompilationStatusManagerService.kt
I removed by mistake javadocs which might be useful, bringing them back
=> chore: bring back javadocs removed by mistake

.github/workflows/validation.yml, plugin/build.gradle.kts, plugin/src/main/kotlin/com/vaadin/plugin/actions/VaadinCompileOnSaveAction.kt, plugin/src/main/kotlin/com/vaadin/plugin/copilot/handler/CompileFilesHandler.kt
As in title, Vaadin should support IDE up to 1 year back.
=> chore: update min supported version to 2024.1

plugin/build.gradle.kts
As in title. Not setting any value resulted in untilVersion == sinceVersion which is wrong.
=> chore: set until version to empty string

plugin/src/main/kotlin/com/vaadin/plugin/actions/InstallJetbrainsRuntimeAction.kt, plugin/src/main/kotlin/com/vaadin/plugin/ui/VaadinStatusBarInfoPopupPanel.kt, plugin/src/main/kotlin/com/vaadin/plugin/utils/JetbrainsRuntimeUtil.kt
Fixes:
```
Vaadin 1.0.0.eap191 invokes APIs marked with @ApiStatus.OverrideOnly, which indicates that the APIs must not be called outside the IntelliJ Platform but only overridden by its clients.
Override-only method usage violation (1)
AnAction.actionPerformed(AnActionEvent) (1)
Override-only method AnAction.actionPerformed(AnActionEvent) is invoked in VaadinStatusBarInfoPopupPanel.createJbrDownloadButton$lambda$2(...). This method is marked with @ApiStatus.OverrideOnly annotation, which indicates that the method must be only overridden but not invoked by client code. See documentation of the @ApiStatus.OverrideOnly for more info.
```
=> fix: Override-only API violation

plugin/src/main/kotlin/com/vaadin/plugin/module/VaadinProjectBuilderAdapter.kt
Based on https://platform.jetbrains.com/t/how-to-distinguish-new-module-from-new-project-using-generator-newprojectwizard-builderadapter/1765/6
=> chore: Use NewProjectAction to detect NewModel / NewProject
