- src/main/kotlin/com/vaadin/plugin/copilot/CopilotPluginUtil.kt
- src/main/kotlin/com/vaadin/plugin/copilot/action/ToggleServerAction.kt
Do not display context menu for non Vaadin applications. Do not require RMB on project folder to manually start copilot plugin.
> feat: Disable action for non Vaadin projects

- src/main/kotlin/com/vaadin/plugin/copilot/CopilotPluginUtil.kt
- src/main/kotlin/com/vaadin/plugin/copilot/handler/AbstractHandler.kt
- src/main/kotlin/com/vaadin/plugin/copilot/handler/RedoHandler.kt
- src/main/kotlin/com/vaadin/plugin/copilot/handler/UndoHandler.kt
- src/main/kotlin/com/vaadin/plugin/copilot/handler/WriteFileHandler.kt
Fixed issue with writing not existing file.
Added logging and fixed issue with copilot plugin not available during new project loading.
> fix: writing non-existing file

- src/main/kotlin/com/vaadin/plugin/copilot/CopilotPluginUtil.kt
Moved .copilot-plugin to .idea, improved logging.
> feat: Store dotfile in .idea

- src/main/kotlin/com/vaadin/plugin/copilot/service/CopilotServerServiceImpl.kt
Using fixed size buffer was causing message truncate during read.
> fix: do not use fixed size buffer

- src/main/kotlin/com/vaadin/plugin/copilot/CopilotPluginUtil.kt
- src/main/kotlin/com/vaadin/plugin/copilot/action/ToggleServerAction.kt
- src/main/kotlin/com/vaadin/plugin/copilot/handler/RedoHandler.kt
- src/main/kotlin/com/vaadin/plugin/copilot/handler/UndoHandler.kt
- src/main/kotlin/com/vaadin/plugin/copilot/handler/WriteFileHandler.kt
Fixes https://github.com/vaadin/copilot-internal/issues/914
> chore: Use Vaadin Copilot (Integration) name

- src/main/kotlin/com/vaadin/plugin/copilot/CopilotErrorHandler.kt
- src/main/kotlin/com/vaadin/plugin/copilot/CopilotPluginUtil.kt
- src/main/resources/META-INF/plugin.xml
User might report feedback by creating GitHub issue:
And resulting issue:
Can be tested with plugin snapshot that always fails on startup:
[intellij-plugin-1.0-SNAPSHOT.zip](https://github.com/vaadin/intellij-plugin/files/14664530/intellij-plugin-1.0-SNAPSHOT.zip)
Fixes #14
> feat: Report submitter

- README.md
> chore: Create README.md

- src/main/kotlin/com/vaadin/plugin/copilot/CopilotErrorHandler.kt
> chore: include OS info in error report

- src/main/kotlin/com/vaadin/plugin/copilot/CopilotPluginUtil.kt
- src/main/kotlin/com/vaadin/plugin/copilot/activity/CopilotPostStartupProjectActivity.kt
- src/main/resources/META-INF/plugin.xml
To test use:
[intellij-plugin-1.0-SNAPSHOT.zip](https://github.com/vaadin/intellij-plugin/files/14744715/intellij-plugin-1.0-SNAPSHOT.zip)
- Open any project that does not have .idea directory.
- Check if .idea directory has been automatically created
- Close project
- Remove .idea directory
- Open project again and make sure plugin has started and .idea folder has been again created
Fixes #20
> fix: Auto create .idea directory

- src/main/kotlin/com/vaadin/plugin/copilot/handler/ShowInIdeHandler.kt
Updated sow in ide:
- clears current selection if any
- scrolls into given line
- bring IDE window to front
Can be tested using [intellij-plugin-1.0-SNAPSHOT.zip](https://github.com/vaadin/intellij-plugin/files/14775521/intellij-plugin-1.0-SNAPSHOT.zip)
> fix: show in ide

- .github/workflows/validation.yml
Use GH Actions for PR validation
> chore: use GH Actions for validation

- src/main/kotlin/com/vaadin/plugin/copilot/action/ToggleServerAction.kt
> fix: Explicitly use EDT on ToggleServerAction

- src/main/kotlin/com/vaadin/plugin/copilot/handler/WriteFileHandler.kt
Compile file on save to allow HotSwap agent reload Java files after being modified.
> feat: Compile on save

- src/main/kotlin/com/vaadin/plugin/copilot/CommandRequest.kt
- src/main/kotlin/com/vaadin/plugin/copilot/CopilotPluginUtil.kt
- src/main/kotlin/com/vaadin/plugin/copilot/RestUtil.kt
- src/main/kotlin/com/vaadin/plugin/copilot/activity/CopilotPostStartupProjectActivity.kt
- src/main/kotlin/com/vaadin/plugin/copilot/service/CopilotRestService.kt
- src/main/kotlin/com/vaadin/plugin/copilot/service/CopilotServerServiceImpl.kt
- src/main/resources/META-INF/plugin.xml
Use embedded rest service instead of plain socket communication.
Kept both for backwards compatibility
> feat: use embedded rest server for handling copilot requests

- .github/workflows/validation.yml
- .gitignore
- build.gradle.kts
- src/main/kotlin/com/vaadin/plugin/module/QuickStarterPanel.kt
- src/main/kotlin/com/vaadin/plugin/module/VaadinProjectBuilderAdapter.kt
- src/main/resources/META-INF/plugin.xml
Use latest intellij platform 2.0.0 api
> chore: update plugin to use new intellij platform api

- .github/workflows/validation.yml
> chore: validation.yml update

- src/main/kotlin/com/vaadin/plugin/starter/QuickStarterModel.kt
Fixes not encoded project name
Fixes #63
> fix: encode project name

- src/main/kotlin/com/vaadin/plugin/activity/ConfigurationCheckPostStartupProjectActivity.kt
- src/main/kotlin/com/vaadin/plugin/copilot/CopilotPluginUtil.kt
- src/main/kotlin/com/vaadin/plugin/hotswapagent/HotswapAgentProgramPatcher.kt
- src/main/kotlin/com/vaadin/plugin/utils/VaadinHomeUtil.kt
- src/main/resources/META-INF/plugin.xml
Checks and replaces if the bundled version is a newer version than the hotswapagent.jar in `~/.vaadin` folder 
Fixes #69
> Check hotswap agent bundle version and updates it if newer version found

- build.gradle.kts
- settings.gradle.kts
> chore: spotless for *.gradle.kts

- src/main/kotlin/com/vaadin/plugin/module/SkeletonStarterPanel.kt
> fix: Revert null check removal

- .github/workflows/validation.yml
Added code checks to validation.yml with spotless validation for the moment
> chore: spotless check

- src/main/kotlin/com/vaadin/plugin/actions/VaadinCompileOnSaveAction.kt
> fix: wrapped hotswap in WriteIntentReadAction

- src/main/kotlin/com/vaadin/plugin/copilot/handler/AbstractHandler.kt
Save document in a way that ActionsOnSave are triggerred.
Fixes https://github.com/vaadin/copilot-internal/issues/2102
> fix: Run actions on save

- src/main/kotlin/com/vaadin/plugin/actions/VaadinCompileOnSaveAction.kt
- src/main/kotlin/com/vaadin/plugin/actions/VaadinCompileOnSaveActionInfo.kt
- src/main/kotlin/com/vaadin/plugin/copilot/handler/WriteFileHandler.kt
- src/main/kotlin/com/vaadin/plugin/listeners/ConfigurationCheckVaadinProjectListener.kt
Do not run compilation explicitly, it is done by "Compile on save" action. Display notification if "Compile on save" is disabled.
> fix: No double compile

- src/main/kotlin/com/vaadin/plugin/hotswapagent/HotswapAgentProgramPatcher.kt
> fix: Add opens for jdk.internal-loader

- src/main/kotlin/com/vaadin/plugin/copilot/listeners/CopilotVaadinProjectListener.kt
> fix: wrap saving dotfile with write action

- src/main/kotlin/com/vaadin/plugin/actions/VaadinCompileOnSaveAction.kt
- src/main/kotlin/com/vaadin/plugin/copilot/handler/AbstractHandler.kt
- src/main/kotlin/com/vaadin/plugin/copilot/handler/WriteBase64FileHandler.kt
- src/main/kotlin/com/vaadin/plugin/utils/VaadinProjectUtil.kt
Copies resources to build directory
Fixes #112
> feat: Copy resources to build directory

- src/main/kotlin/com/vaadin/plugin/copilot/CopilotPluginUtil.kt
- src/main/kotlin/com/vaadin/plugin/copilot/handler/GetSourcePathsHandler.kt
- src/main/kotlin/com/vaadin/plugin/copilot/handler/HandlerResponse.kt
> feat: Handler for getting all source paths

- gradle/wrapper/gradle-wrapper.properties
> deps: bump gradle to 8.11.1

- .github/workflows/validation.yml
- build.gradle.kts
- src/main/resources/META-INF/plugin.xml
- src/main/resources/META-INF/vaadin-with-microservices.xml
Separate Ultimate features (Vaadin Endpoints)
Fixes #178 
Fixes #179
> fix: separate ultimate parts

- README.md
- src/main/resources/META-INF/plugin.xml
Update description to cover current features of plugin
> chore: Description update

- src/main/kotlin/com/vaadin/plugin/actions/DebugUsingHotSwapAgentAction.kt
- src/main/kotlin/com/vaadin/plugin/hotswapagent/HotswapAgentExecutor.kt
> Revert "fix: hotswap only for java run configurations (#176)"

- src/main/kotlin/com/vaadin/plugin/ui/VaadinStatusBarInfoPopupPanel.kt
- src/main/kotlin/com/vaadin/plugin/ui/VaadinStatusBarWidget.kt
> ref: Do not use internal API for icon badge

- src/main/kotlin/com/vaadin/plugin/copilot/CopilotPluginUtil.kt
findOrCreateDirectory has been wrapped in write action when creating .copilot-plugin file. Added flag not to create that directory if not needed.
Fixes: #205
> fix: Do not try to create .idea directory when not saving .copilot-plugin file

- src/main/kotlin/com/vaadin/plugin/copilot/listeners/CopilotVaadinProjectListener.kt
> fix: Do not create Copilot dotfile for disposed projects

- build.gradle.kts
> chore: bump intellij platform to 2.2.0

- build.gradle.kts
> fix: Exclude JNA

- src/main/kotlin/com/vaadin/plugin/copilot/CopilotErrorHandler.kt
As in title to help investigating plugin issues
> chore: Add JVM info and OS version to GH error report template

- .github/workflows/validation.yml
- build.gradle.kts
- src/main/resources/META-INF/plugin.xml
Update to support upcoming IntelliJ 2025.1
> chore: Update until to support 2025.1 (251)

- src/main/resources/META-INF/plugin.xml
> fix: hotswap icon

- src/main/kotlin/com/vaadin/plugin/actions/VaadinCompileOnSaveActionInfo.kt
- src/main/kotlin/com/vaadin/plugin/copilot/CopilotPluginUtil.kt
- src/main/kotlin/com/vaadin/plugin/copilot/handler/CompileFilesHandler.kt
> feat: compileFiles command

- .github/workflows/validation.yml
> chore: Do not print full compatibility logs, fail on not compatible

- src/main/kotlin/com/vaadin/plugin/hotswapagent/HotswapAgentProgramPatcher.kt
List from https://github.com/HotswapProjects/HotswapAgent/issues/633#issuecomment-2601957454
> chore: Sync add-opens with what JBR uses

- plugin/build.gradle.kts
> dep: Use stable spotless

- plugin/src/main/kotlin/com/vaadin/plugin/utils/VaadinHomeUtil.kt
> fix: Create proper userKey file

- plugin/src/main/kotlin/com/amplitude/ampli/Ampli.kt
- plugin/src/main/kotlin/com/vaadin/plugin/hotswapagent/HotswapAgentRunner.kt
- plugin/src/main/kotlin/com/vaadin/plugin/utils/AmpliUtil.kt
> chore: Debug with Hotswap usage stats

- plugin/src/main/kotlin/com/vaadin/plugin/starter/HelloWorldModel.kt
- plugin/src/main/kotlin/com/vaadin/plugin/starter/StarterProjectModel.kt
As in title, will allow to distinguish downloads from different IDEs.
> chore: Add referer to starter downloads urls

- plugin/src/main/kotlin/com/vaadin/plugin/hotswapagent/HotswapAgentRunner.kt
> fix: Prepare hotswap runner in background before launching

- plugin/src/main/kotlin/com/vaadin/plugin/copilot/CopilotPluginUtil.kt
- plugin/src/main/kotlin/com/vaadin/plugin/copilot/service/CopilotDotfileServiceImpl.kt
> fix: Create .idea directory if not exists

- plugin/src/main/kotlin/com/vaadin/plugin/copilot/service/CopilotRestService.kt
As in title, might help debugging similar issues in future
> chore: Log more info in case of project not found

- plugin/src/main/kotlin/com/vaadin/plugin/utils/VaadinHomeUtil.kt
> fix: Automatically fix userKey issue

- plugin/src/main/kotlin/com/vaadin/plugin/hotswapagent/HotswapAgentExecutor.kt
Fixes: https://github.com/vaadin/copilot/issues/80
> chore: Add Debug using Hotswap to "Current File" run config

- plugin-api-test-client/src/test/java/com/vaadin/plugin/PluginApiTests.java
- plugin/src/main/kotlin/com/vaadin/plugin/copilot/handler/UndoHandler.kt
Will contribute to fixing Copilot issue related to view reloading when there is nothing to undo/redo.
> chore: return information if undo/redo has been performed

- .github/workflows/validation.yml
- plugin/build.gradle.kts
> chore: Remove untilBuild limit

- plugin/src/main/kotlin/com/vaadin/plugin/actions/InstallJetbrainsRuntimeAction.kt
- plugin/src/main/kotlin/com/vaadin/plugin/hotswapagent/JdkUtil.kt
- plugin/src/main/kotlin/com/vaadin/plugin/starter/StarterProjectModel.kt
- plugin/src/main/kotlin/com/vaadin/plugin/ui/VaadinStatusBarInfoPopupPanel.kt
- plugin/src/main/kotlin/com/vaadin/plugin/ui/VaadinStatusBarWidget.kt
- plugin/src/main/kotlin/com/vaadin/plugin/utils/JetbrainsRuntimeUtil.kt
- plugin/src/main/kotlin/com/vaadin/plugin/utils/VaadinHomeUtil.kt
- plugin/src/main/resources/META-INF/plugin.xml
This PR introduces new action **JetBrains Runtime: Install Latest Version** and adds to status bar widget JBR check result. If current SDK is not JBR or there is no SDK configured, offer automated download and setup.
JBR update notifications will be done in separate PR.
> feat: Automated download and setup of JBR

- plugin/build.gradle.kts
> chore: Use Java 21 in 2024.2

- plugin/src/main/kotlin/com/vaadin/plugin/ui/VaadinChatAppToolWindowFactory.kt
- plugin/src/main/resources/META-INF/plugin.xml
Embedded web view for AI chat inside tool window
> chore: Copilot AI Chat as Tool Window

- .github/workflows/validation.yml
- .idea/compiler.xml
- .idea/misc.xml
- plugin/build.gradle.kts
- plugin/src/main/kotlin/com/vaadin/plugin/listeners/ConfigurationCheckVaadinProjectListener.kt
- plugin/src/main/kotlin/com/vaadin/plugin/utils/IdeUtil.kt
Will allow to use Starter API for writing simple integration tests.
> deps: Bump platform to 2024.2 (sinceBuild)
